#ifndef FIRMWARE_VERSION_H
#define FIRMWARE_VERSION_H

#ifndef CREATIVE_FW_VERSION
#define CREATIVE_FW_VERSION "SN986_1.20_85a_20170120_1237"
#endif

#ifndef CREATIVE_CONSTPARA
#define CREATIVE_CONSTPARA 1
#endif

#endif
