#ifndef _MAIN_H
#define _MAIN_H

#define LINE_MAX_LENGTH 500
#define READ_LENGTH 502

#define ADDRESS_MAX_LENGTH 50
#define TYPE_MAX_LENGTH 300
#define FILE_MAX_LENGTH 300

#define ACTUAL_ADDRESS_LENGTH 10
#define SECTION_COUNT 4

#define PADNAME_MAX_LENGTH 300
#define PADVALUE_MAX_LENGTH 300
#define PADTYPE_MAX_LENGTH 300

#define ACTUAL_PADVALUE_LENGTH 4
#define ROOTFS_R__LENGTH 11

#define COMMON_SECTION_LENGTH 8

#endif /* _MAIN_H */
